[".local/share/fcitx5"]
    type = "archive"
    url = "http://ys-g.ysepan.com/wap/huma/Nki9D4UE2TcP5fD4EC/9c4gC9iq3gEhFSabds2IDEb6iA1iE3/fcitx5.zip"
    stripComponents = 1
    exact = true
    refreshPeriod = "168h"
